# Workflow setup for building Native Android project
workflows:
    android-app: # workflow ID
        name: Android app # workflow name
        scripts:                                      
            - name: build your app without sigining 
              script: | 
                  chmod +x gradlew
                 ./gradlew sonarqube -Dsonar.projectKey=abkhan -Dsonar.host.url=http://localhost:9000  -Dsonar.login=72202ffde6987e4fc5f610d09c042deb67752a15 
                 ./gradlew assembleDebug
         
        artifacts:
           - app/build/**/outputs/**/*.apk


